### ISSUE TITLE
File naming for views

### ISSUE THREAD

**Issue by pabloqb** [OCA/odoo-community.org#30]
According to section 1.5 File naming
> ... in XML files, a suffix should be included with its category. For model named <main_model> the following files may be created: `views/<main_model>_view.xml`

In this point the suffix is singular mode **view**. However the complete tree structure states:
```
|-- views/
|   |-- <main_model>.xml
|   |-- <inherited_main_model>_views.xml
```
There is no suffix for **main_model.xml** and it is in plural for the inherited_main_model_**views**.xml example.

Which would be the correct way?

Best,
Pablo.

**Comment by pedrobaeza** [comment]
Thanks for pointing this out. Most of the documentation is in singular, but I prefer plural, as it expresses more what contains: it can be more than one view inside the XML file.

@OCA/board what do you think about this?

**Comment by max3903** [comment]
I don't see the point of repeating view in `<inherited_main_model>_views.xml`. We already know it is a view as it is in the `views` directory.

I would make a change to have:

```
|-- views/
|   |-- <main_model>.xml
|   |-- <inherited_main_model>.xml
```

**Comment by pedrobaeza** [comment]
@max3903 this has been discussed other times, and it's because if you perform a file name search, you want to know which can of data it is: demo, data, views, etc.

**Comment by max3903** [comment]
ok, then
```
|-- views/
|   |-- <main_model>_view.xml
|   |-- <inherited_main_model>_view.xml
```

**Comment by pedrobaeza** [comment]
So, you prefer in singular? Have you seen my argument about the plural?

**Comment by max3903** [comment]
As you said, the idea is to know the kind of data, not if there is one or more record.

**Comment by pedrobaeza** [comment]
OK, let's be inline with module naming in singular. Any other opinion?

**Comment by Tardo** [comment]
I prefer use "views" because normally a "view .xml" defines multiple views.. The 'basics' are "form" and "tree" views...
Perhaps can use "view" for new view definition (google maps view, calendar view, etc..)

Filter "_views" to know files that implement or inherit (if have the inhertied_ prefix) a Odoo base view type
Filter "_view" to know files that implement a new view type

I have other questions about Code Guidelines... for example.. where is the correct site to define "actions"?? in the same _view/s.xml file or separate it? perhaps best open other issue for this questions?

**Comment by pedrobaeza** [comment]
@Tardo about this topic, it's better to keep only one way of naming things (plural or singular), because if not, it's more difficult to know which to use, and would force also to rename if we change conditions of the files, etc.

About the other thing, better to open a new issue and to not mix things :wink:

**Comment by Tardo** [comment]
@pedrobaeza ok, it makes sense what you say. 
Odoo uses "views" in their guidelines... https://www.odoo.com/documentation/12.0/reference/guidelines.html#file-naming

**Comment by pedrobaeza** [comment]
If Odoo uses plural then I think we should stick to that. @max3903 what do you think?

**Comment by max3903** [comment]
Ok

**Comment by sbidoul** [comment]
Yes, alignement with Odoo guidelines is a good thing in general.

**Comment by pabloqb** [comment]
Thank you for the feedbacks and indications. 

Best, 
Pablo.
